# Jekyll Configuration
safe: true
markdown: rdiscount
pigments: true
permalink: pretty
exclude:
    - node_modules
    - Gruntfile.js
    - bower.json
    - package.json

# Site
name: Masega
baseurl: http://masegalab.github.io/
